apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dhz003d0z-python 
  janus-idp.io/tekton: dhz003d0z-python
  backstage.io/kubernetes-id: dhz003d0z-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dhz003d0z-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  