apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dhz003d0z-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dhz003d0z-python 
  name: dhz003d0z-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dhz003d0z-python 
